### ISSUE TITLE
Adding two domains to LETSENCRYPT_HOST breaks proxy-companion

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-compose-letsencrypt-nginx-proxy-companion#7]
adding `LETSENCRYPT_HOST=csis.ait.ac.at,csis.clarity.cismet.de` results in

> nginx-letsencrypt    | Creating/renewal csis.ait.ac.at certificates... (csis.ait.ac.at csis.clarity.cismet.de)
nginx-letsencrypt    | 2020/02/07 11:31:44 Received event start for container 0e52378dda55
nginx-letsencrypt    | 2020-02-07 11:31:44,116:INFO:simp_le:1414: Generating new certificate private key
nginx-letsencrypt    | 2020/02/07 11:31:44 Received event die for container 0e52378dda55
nginx-letsencrypt    | 2020/02/07 11:31:45 Received event start for container 0e52378dda55
nginx-letsencrypt    | 2020/02/07 11:31:45 Received event die for container 0e52378dda55
nginx-letsencrypt    | 2020-02-07 11:31:47,460:ERROR:simp_le:1396: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Are all your domains accessible from the internet? Please check your domains' DNS entries, your host's network/firewall setup and your webserver config. If a domain's DNS entry has both A and AAAA fields set up, some CAs such as Let's Encrypt will perform the challenge validation over IPv6. If your DNS provider does not answer correctly to CAA records request, Let's Encrypt won't issue a certificate for your domain (see https://letsencrypt.org/docs/caa/). Failing authorizations: https://acme-v02.api.letsencrypt.org/acme/authz-v3/2689925829

and

> nginx-web            | nginx: [emerg] cannot load certificate "/etc/nginx/certs/csis.ait.ac.at.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/certs/csis.ait.ac.at.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)

**Comment by p-a-s-c-a-l** [comment]
Never change a running system! After removing 2nd domain from `LETSENCRYPT_HOST`:
> nginx-letsencrypt    | 2020-02-07 11:45:54,824:INFO:simp_le:1414: Generating new certificate private key
nginx-letsencrypt    | 2020-02-07 11:45:58,337:ERROR:simp_le:1396: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Are all your domains accessible from the internet? Please check your domains' DNS entries, your host's network/firewall setup and your webserver config. If a domain's DNS entry has both A and AAAA fields set up, some CAs such as Let's Encrypt will perform the challenge validation over IPv6. If your DNS provider does not answer correctly to CAA records request, Let's Encrypt won't issue a certificate for your domain (see https://letsencrypt.org/docs/caa/). Failing authorizations: https://acme-v02.api.letsencrypt.org/acme/authz-v3/2690098044

**Comment by p-a-s-c-a-l** [comment]
> "Invalid response from https://csis.ait.ac.at/.well-known/acme-challenge/uYA0vExyFVMrzfkdv0LqB-CqWS7zCxWjAuy1jOU2vpk [62.218.164.247]: \"<html>\\r\\n<head><title>500 Internal Server Error</title></head>\\r\\n<body>\\r\\n<center><h1>500 Internal Server Error</h1></center>\\r\\n<hr>\""

**Comment by p-a-s-c-a-l** [comment]
Still broken after taking the ['atomic nuke option'](https://github.com/clarity-h2020/docker-compose-letsencrypt-nginx-proxy-companion/blob/csis.ait.ac.at/nuke.sh):

> nginx-letsencrypt    | 2020-02-07 13:14:30,357:ERROR:simp_le:1396: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Are all your domains accessible from the internet? Please check your domains' DNS entries, your host's network/firewall setup and your webserver config. If a domain's DNS entry has both A and AAAA fields set up, some CAs such as Let's Encrypt will perform the challenge validation over IPv6. If your DNS provider does not answer correctly to CAA records request, Let's Encrypt won't issue a certificate for your domain (see https://letsencrypt.org/docs/caa/). Failing authorizations: https://acme-v02.api.letsencrypt.org/acme/authz-v3/2691193142

**Comment by p-a-s-c-a-l** [comment]
> "Fetching http://csis.ait.ac.at/.well-known/acme-challenge/ZiT8VMCpOrOVKM6A0tneBpd-DW-avK9QEzevX-ToFTQ: Connection refused"

**Comment by p-a-s-c-a-l** [comment]
@Itsman-AT Please ensure that port 80 incoming is allowed for 62.218.164.246 and 62.218.164.247 .

**Comment by p-a-s-c-a-l** [comment]
```sh
curl -v https://csis-dev.ait.ac.at
* Rebuilt URL to: https://csis-dev.ait.ac.at/
*   Trying 62.218.164.246...
* TCP_NODELAY set
* Connected to csis-dev.ait.ac.at (62.218.164.246) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Unknown (8):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, Server hello (2):
* SSL certificate problem: self signed certificate
* stopped the pause stream!
* Closing connection 0
curl: (60) SSL certificate problem: self signed certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by p-a-s-c-a-l** [comment]
Still getting 
> nginx-letsencrypt    | 2020-02-07 13:45:00,895:ERROR:simp_le:1396: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Are all your domains accessible from the internet? Please check your domains' DNS entries, your host's network/firewall setup and your webserver config. If a domain's DNS entry has both A and AAAA fields set up, some CAs such as Let's Encrypt will perform the challenge validation over IPv6. If your DNS provider does not answer correctly to CAA records request, Let's Encrypt won't issue a certificate for your domain (see https://letsencrypt.org/docs/caa/). Failing authorizations: https://acme-v02.api.letsencrypt.org/acme/authz-v3/2691525574

https://csis-dev.ait.ac.at/.well-known/acme-challenge/4UsZGjBuxXZo_5_Np9vefwpErrioWiEnC9qSZ2tMLuk

-> 500 Internal Server Error

**Comment by p-a-s-c-a-l** [comment]
> nginx-letsencrypt    | Challenge validation has failed, see error log.
nginx-letsencrypt    |
nginx-letsencrypt    | Debugging tips: -v improves output verbosity. Help is available under --help.

Where are the logs? where to append the -v option?

**Comment by p-a-s-c-a-l** [comment]
@therter @jeanatcismet 

Any idea what is going on here? Are there more logs? Where? `data/logs/error.log` is empty.

**Comment by p-a-s-c-a-l** [comment]
Removed vhost.d directory with custom configuration and it's working but it did work with the very same configuration before ?!

**Comment by p-a-s-c-a-l** [comment]
-> remove all symlinks in vhost.d. Don't use git symlinks any more.

**Comment by p-a-s-c-a-l** [comment]
Again:

> nginx-letsencrypt    | 2020-02-10 08:04:14,667:ERROR:simp_le:1396: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Are all your domains accessible from the internet? Please check your domains' DNS entries, your host's network/firewall setup and your webserver config. If a domain's DNS entry has both A and AAAA fields set up, some CAs such as Let's Encrypt will perform the challenge validation over IPv6. If your DNS provider does not answer correctly to CAA records request, Let's Encrypt won't issue a certificate for your domain (see https://letsencrypt.org/docs/caa/). Failing authorizations: https://acme-v02.api.letsencrypt.org/acme/authz-v3/2738384011, https://acme-v02.api.letsencrypt.org/acme/authz-v3/2738384014

-> 500 Internal Server Error

**Comment by p-a-s-c-a-l** [comment]
`docker logs nginx-web`: nothing!

**Comment by p-a-s-c-a-l** [comment]
`more /var/log/nginx/error.log`: empty.

Probably a problem in the configuration files in in vhost.d, but this seems impossible to debug.

**Comment by p-a-s-c-a-l** [comment]
Getting closer:

```
nginx-web            | nginx: [emerg] unexpected end of file, expecting ";" or "}" in /etc/nginx/vhost.d/csis-dev.ait.ac.at:1
nginx-web            | nginx: [emerg] unexpected end of file, expecting ";" or "}" in /etc/nginx/vhost.d/csis-dev.ait.ac.at:1
nginx-web            | nginx: [emerg] unexpected end of file, expecting ";" or "}" in /etc/nginx/vhost.d/csis-dev.ait.ac.at:1
nginx-web            | nginx: [emerg] unexpected end of file, expecting ";" or "}" in /etc/nginx/vhost.d/csis-dev.ait.ac.at:11
nginx-web            | nginx: [emerg] unexpected end of file, expecting ";" or "}" in /etc/nginx/vhost.d/csis-dev.ait.ac.at:11
nginx-web            | nginx: [emerg] unexpected end of file, expecting ";" or "}" in /etc/nginx/vhost.d/csis-dev.ait.ac.at:11
nginx-web            | nginx: [emerg] unexpected end of file, expecting ";" or "}" in /etc/nginx/vhost.d/csis-dev.ait.ac.at:11
nginx-web            | nginx: [emerg] unexpected end of file, expecting ";" or "}" in /etc/nginx/vhost.d/csis-dev.ait.ac.at:11
nginx-web            | nginx: [emerg] unexpected end of file, expecting ";" or "}" in /etc/nginx/vhost.d/csis-dev.ait.ac.at:11
nginx-web            | nginx: [emerg] open() "/etc/nginx/vhost.d/csis-dev.ait.ac.at" failed (2: No such file or directory) in /etc/nginx/conf.d/default.conf:74
nginx-web            | nginx: [emerg] open() "/etc/nginx/vhost.d/csis-dev.ait.ac.at" failed (2: No such file or directory) in /etc/nginx/conf.d/default.conf:74
nginx-web            | nginx: [emerg] open() "/etc/nginx/vhost.d/csis-dev.ait.ac.at" failed (2: No such file or directory) in /etc/nginx/conf.d/default.conf:74
nginx-web            | nginx: [emerg] open() "/etc/nginx/vhost.d/csis-dev.ait.ac.at" failed (2: No such file or directory) in /etc/nginx/conf.d/default.conf:74
nginx-web            | nginx: [emerg] open() "/etc/nginx/vhost.d/csis-dev.ait.ac.at" failed (2: No such file or directory) in /etc/nginx/conf.d/default.conf:74
nginx-web            | nginx: [emerg] open() "/etc/nginx/vhost.d/csis-dev.ait.ac.at" failed (2: No such file or directory) in /etc/nginx/conf.d/default.conf:74
nginx-web            | nginx: [emerg] open() "/etc/nginx/vhost.d/csis-dev.ait.ac.at" failed (2: No such file or directory) in /etc/nginx/conf.d/default.conf:74
nginx-web            | nginx: [emerg] open() "/etc/nginx/vhost.d/csis-dev.ait.ac.at" failed (2: No such file or directory) in /etc/nginx/conf.d/default.conf:74
nginx-web            | nginx: [emerg] open() "/etc/nginx/vhost.d/csis-dev.ait.ac.at" failed (2: No such file or directory) in /etc/nginx/conf.d/default.conf:74
nginx-web            | nginx: [emerg] open() "/etc/nginx/vhost.d/csis-dev.ait.ac.at" failed (2: No such file or directory) in /etc/nginx/conf.d/default.conf:74
```

**Comment by Itsman-AT** [comment]
Is this configuration sufficient?
![grafik](https://user-images.githubusercontent.com/41750112/74137948-00bfe900-4bf1-11ea-80c7-8571d4750b7b.png)

**Comment by p-a-s-c-a-l** [comment]
No chance:
> nginx-letsencrypt    | 2020-02-10 12:37:03,208:ERROR:simp_le:1396: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Are all your domains accessible from the internet? Please check your domains' DNS entries, your host's network/firewall setup and your webserver config. If a domain's DNS entry has both A and AAAA fields set up, some CAs such as Let's Encrypt will perform the challenge validation over IPv6. If your DNS provider does not answer correctly to CAA records request, Let's Encrypt won't issue a certificate for your domain (see https://letsencrypt.org/docs/caa/). Failing authorizations: https://acme-v02.api.letsencrypt.org/acme/authz-v3/2741845094, https://acme-v02.api.letsencrypt.org/acme/authz-v3/2741845095

**Comment by Itsman-AT** [comment]
>  Please check your domains' DNS entries, your host's network/firewall setup and your webserver config. If a domain's DNS entry has both A and AAAA fields set up, some CAs such as Let's Encrypt will perform the challenge validation over IPv6. If your DNS provider does not answer correctly to CAA records request, Let's Encrypt won't issue a certificate for your domain

@p-a-s-c-a-l : I can check back with our ITO, if you want, to be clear that there is no issue with AIT's firewall here.

**Comment by p-a-s-c-a-l** [comment]
resolved. maybe. [maybe not](https://github.com/clarity-h2020/docker-compose-letsencrypt-nginx-proxy-companion/issues/8#issuecomment-584194049). 🤦‍♂
