### ISSUE TITLE
nginx-letsencrypt-proxy broken beyond repair

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-compose-letsencrypt-nginx-proxy-companion#8]
nginx-letsencrypt is broken not only for the [new configurations used for csis.ait.ac.at and csis-dev.ait.ac.at](https://github.com/clarity-h2020/docker-compose-letsencrypt-nginx-proxy-companion/issues/7) but now also for **myclimateservice.eu** and all of its subdomains. 

It is impossible to create new certificates:
> nginx-letsencrypt    | 2020-02-10 13:07:55,459:ERROR:simp_le:1396: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Are all your domains accessible from the internet? Please check your domains' DNS entries, your host's network/firewall setup and your webserver config. If a domain's DNS entry has both A and AAAA fields set up, some CAs such as Let's Encrypt will perform the challenge validation over IPv6. If your DNS provider does not answer correctly to CAA records request, Let's Encrypt won't issue a certificate for your domain (see https://letsencrypt.org/docs/caa/). Failing authorizations: https://acme-v02.api.letsencrypt.org/acme/authz-v3/2742252540
nginx-letsencrypt    | 2020-02-10 13:07:55,462:INFO:simp_le:396: Saving account_key.json
nginx-letsencrypt    | 2020-02-10 13:07:55,463:INFO:simp_le:396: Saving account_reg.json
nginx-letsencrypt    | Challenge validation has failed, see error log.
nginx-letsencrypt    |
nginx-letsencrypt    | Debugging tips: -v improves output verbosity. Help is available under --help.
nginx-letsencrypt    | /app
nginx-letsencrypt    | /etc/nginx/certs/csis.myclimateservice.eu /app
nginx-letsencrypt    | Creating/renewal csis.myclimateservice.eu certificates... (csis.myclimateservice.eu)
nginx-letsencrypt    | 2020-02-10 13:07:56,618:INFO:simp_le:1414: Generating new certificate private key
nginx-letsencrypt    | 2020-02-10 13:07:59,575:ERROR:simp_le:1396: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Are all your domains accessible from the internet? Please check your domains' DNS entries, your host's network/firewall setup and your webserver config. If a domain's DNS entry has both A and AAAA fields set up, some CAs such as Let's Encrypt will perform the challenge validation over IPv6. If your DNS provider does not answer correctly to CAA records request, Let's Encrypt won't issue a certificate for your domain (see https://letsencrypt.org/docs/caa/). Failing authorizations: https://acme-v02.api.letsencrypt.org/acme/authz-v3/2742253245
nginx-letsencrypt    | Challenge validation has failed, see error log.
nginx-letsencrypt    |
nginx-letsencrypt    | Debugging tips: -v improves output verbosity. Help is available under --help.
nginx-letsencrypt    | /app
nginx-letsencrypt    | /etc/nginx/certs/geoserver.myclimateservice.eu /app
nginx-letsencrypt    | Creating/renewal geoserver.myclimateservice.eu certificates... (geoserver.myclimateservice.eu)
nginx-letsencrypt    | 2020-02-10 13:08:00,837:INFO:simp_le:1414: Generating new certificate private key
nginx-letsencrypt    | 2020-02-10 13:08:03,454:ERROR:simp_le:1396: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Are all your domains accessible from the internet? Please check your domains' DNS entries, your host's network/firewall setup and your webserver config. If a domain's DNS entry has both A and AAAA fields set up, some CAs such as Let's Encrypt will perform the challenge validation over IPv6. If your DNS provider does not answer correctly to CAA records request, Let's Encrypt won't issue a certificate for your domain (see https://letsencrypt.org/docs/caa/). Failing authorizations: https://acme-v02.api.letsencrypt.org/acme/authz-v3/2742253977

Getting 'connecting refused', e.g. when calling the following ACME challenge URL : http://ckan.myclimateservice.eu/.well-known/acme-challenge/N-bWLjjdxXEEM0wOY9bHAY1DqgQc58P-4cPY_nL28OE: Connection refused

nginx is running: 
`nginx-web           nginx -g daemon off;             Up       81.189.135.173:443->443/tcp, 81.189.135.173:80->80/tcp`

but getting even connection refused when trying to access http://localhost:80. ?!

**Comment by Itsman-AT** [comment]
I am already checking with the ITO.

**Comment by p-a-s-c-a-l** [comment]
Adding 'VIRTUAL_PORT=8080' to .env of csis-docker  now seems to be mandatory. :hurtrealbad:

**Comment by p-a-s-c-a-l** [comment]
[This workaround](https://github.com/clarity-h2020/docker-compose-letsencrypt-nginx-proxy-companion/issues/4) for [this Drupal problem](https://github.com/clarity-h2020/docker-drupal/issues/57) seems to **silently** break default.conf. :hurtrealbad:

**Comment by p-a-s-c-a-l** [comment]
![grafik](https://user-images.githubusercontent.com/1788226/74157842-4395b700-4c19-11ea-8534-c691ba4b0e73.png)

**No, it doesn't**! Forwarding to Drupal docker container **does not** work, despite the generate default.conf tells otherwise:

```
# csis.myclimateservice.eu
upstream csis.myclimateservice.eu {
				## Can be connected with "clarity" network
			# csis-drupal
			server 172.19.0.16:80;
				## Can be connected with "clarity" network
			# test-web
			server 172.19.0.2:80;
}
server {
	server_name csis.myclimateservice.eu;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	# Do not HTTPS redirect Let'sEncrypt ACME challenge
	location /.well-known/acme-challenge/ {
		auth_basic off;
		allow all;
		root /usr/share/nginx/html;
		try_files $uri =404;
		break;
	}
	location / {
		return 301 https://$host$request_uri;
	}
}
server {
	server_name csis.myclimateservice.eu;
	listen 443 ssl http2 ;
	access_log /var/log/nginx/access.log vhost;
	ssl_session_timeout 5m;
	ssl_session_cache shared:SSL:50m;
	ssl_session_tickets off;
	ssl_certificate /etc/nginx/certs/csis.myclimateservice.eu.crt;
	ssl_certificate_key /etc/nginx/certs/csis.myclimateservice.eu.key;
	ssl_dhparam /etc/nginx/certs/csis.myclimateservice.eu.dhparam.pem;
	ssl_stapling on;
	ssl_stapling_verify on;
	ssl_trusted_certificate /etc/nginx/certs/csis.myclimateservice.eu.chain.pem;
	add_header Strict-Transport-Security "max-age=31536000" always;
	include /etc/nginx/vhost.d/csis.myclimateservice.eu;
	location / {
		proxy_pass http://csis.myclimateservice.eu;
	}
}
```

**Comment by p-a-s-c-a-l** [comment]
https://csis.myclimateservice.eu/ working again, but no chance with https://csis-dev.ait.ac.at/ :

> nginx-letsencrypt    | 2020-02-10 14:46:45,272:ERROR:simp_le:1396: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Are all your domains accessible from the internet? Please check your domains' DNS entries, your host's network/firewall setup and your webserver config. If a domain's DNS entry has both A and AAAA fields set up, some CAs such as Let's Encrypt will perform the challenge validation over IPv6. If your DNS provider does not answer correctly to CAA records request, Let's Encrypt won't issue a certificate for your domain (see https://letsencrypt.org/docs/caa/). Failing authorizations: https://acme-v02.api.letsencrypt.org/acme/authz-v3/2743433202

**Comment by p-a-s-c-a-l** [comment]
> curl -v localhost
> * Rebuilt URL to: localhost/
> *   Trying ::1...
> * TCP_NODELAY set
> * connect to ::1 port 80 failed: Connection refused
> *   Trying 127.0.0.1...
> * TCP_NODELAY set
> * connect to 127.0.0.1 port 80 failed: Connection refused
> * Failed to connect to localhost port 80: Connection refused
> * Closing connection 0
> curl: (7) Failed to connect to localhost port 80: Connection refused

> docker-compose ps
>       Name                     Command               State                            Ports
> nginx-gen           /usr/local/bin/docker-gen  ...   Exit 2
> nginx-letsencrypt   /bin/bash /app/entrypoint. ...   Up
> nginx-web           nginx -g daemon off;             Up       62.218.164.246:443->443/tcp, 62.218.164.246:80->80/tcp


?!? 🤕

**Comment by p-a-s-c-a-l** [comment]
> 36bc428c1639        nginx                                    "nginx -g 'daemon of…"   About a minute ago   Up About a minute   62.218.164.246:80->80/tcp, 62.218.164.246:443->443/tcp   nginx-web

`curl nginx-web` -> connection refused.

It seems that although nginx-web container is running, the nginx process inside of the container is not. There are no logs. So what's going on?

**Comment by p-a-s-c-a-l** [comment]
```sh
docker exec -it nginx-web bash
root@36bc428c1639:/# ps
bash: ps: command not found
root@36bc428c1639:/# top
bash: top: command not found
root@36bc428c1639:/#

```

**Comment by p-a-s-c-a-l** [comment]
```json
{
  "identifier": {
    "type": "dns",
    "value": "csis-dev.ait.ac.at"
  },
  "status": "invalid",
  "expires": "2020-02-17T15:05:52Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "invalid",
      "error": {
        "type": "urn:ietf:params:acme:error:connection",
        "detail": "Fetching http://csis-dev.ait.ac.at/.well-known/acme-challenge/QOXMXUXPD1wKwpnNUNwe2g2GhzynGJqjewSzWPRaMnI: Connection refused",
        "status": 400
      },
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/2743663714/oLJzSg",
      "token": "QOXMXUXPD1wKwpnNUNwe2g2GhzynGJqjewSzWPRaMnI",
      "validationRecord": [
        {
          "url": "http://csis-dev.ait.ac.at/.well-known/acme-challenge/QOXMXUXPD1wKwpnNUNwe2g2GhzynGJqjewSzWPRaMnI",
          "hostname": "csis-dev.ait.ac.at",
          "port": "80",
          "addressesResolved": [
            "62.218.164.246"
          ],
          "addressUsed": "62.218.164.246"
        }
      ]
    }
  ]
}
```

**Comment by Itsman-AT** [comment]
@p-a-s-c-a-l : Just a wild guess: The only difference between the machines is the difference in Linux version numbers, the "old" server is 16.04 LTS, the new one 18.04 LTS. Are you using the nginx conf file in your home directory? Or the one within the container? Are there maybe differences in the configuration between those two Ubuntu versions?

**Comment by p-a-s-c-a-l** [comment]
https://csis-dev.clarity.cismet.de/.well-known/acme-challenge/cyway8St4FcCXAXKe9U_0liXXSEoik_38d0whsY460Y 
> The provided host name is not valid for this server. 

That's a Drupal back-end error message

But in vhost.d/csis-dev.clarity.cismet.de:
```
## Start of configuration add by letsencrypt container
location ^~ /.well-known/acme-challenge/ {
    auth_basic off;
    auth_request off;
    allow all;
    root /usr/share/nginx/html;
    try_files $uri =404;
    break;
}
## End of configuration add by letsencrypt container
```

It seems that this location block is ignored. Or not added to default.conf or whatever.

**Comment by p-a-s-c-a-l** [comment]
>  Are there maybe differences in the configuration between those two Ubuntu versions?

That's the reason why we use docker: it doesn't matter if you use the same images. But in this particular case, it doesn't work. This proxy-companion automatically generates nginx configurations which from time to time may or may not work and there is no information why (no logs, no error messages).

**Comment by p-a-s-c-a-l** [comment]
@therter @jeanatcismet 
Any idea how to debug nginx-web? The container starts but the process [perhaps not](https://github.com/clarity-h2020/docker-compose-letsencrypt-nginx-proxy-companion/issues/8#issuecomment-584164236). 

Some of [these config files](https://github.com/clarity-h2020/docker-compose-letsencrypt-nginx-proxy-companion/tree/csis-dev.ait.ac.at/nginx-data/vhost.d) *may* break nginx.

**Comment by therter** [comment]
> The container starts but the process [perhaps not](https://github.com/clarity-h2020/docker-compose-letsencrypt-nginx-proxy-companion/issues/8#issuecomment-584164236).


you can install the top and ps command within the container with

```
apt-get update
apt-get install procps
```

After that, you can check if the nginx process is running

**Comment by p-a-s-c-a-l** [comment]
```
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 15:34 ?        00:00:00 nginx: master process nginx -g daemon off;
nginx       10     1  0 15:34 ?        00:00:00 nginx: worker process
root        11     0  0 15:44 pts/0    00:00:00 bash
root       590    11  0 15:45 pts/0    00:00:00 ps -ef
```

`curl localhost` **inside** container:

```htm
<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx/1.17.8</center>
</body>
</html>
```

but why?

**Comment by p-a-s-c-a-l** [comment]
After a lot of trial error, deleting configuration, containers, networks, reboots, using / not using start.sh creating new .env files, clean checkouts, etc. it suddenly started working. Still, I have no idea why it works and why it didn't before.

**Comment by Itsman-AT** [comment]
Well done!
